### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'scale'

### ISSUE THREAD

**Issue by qinqinqaq** [OpenBMB/CPM-Live#380]
AdamOffloadOptimizer is no such parameter: scale

self.optimizer = bmt.optim.AdamOffloadOptimizer(
            model.parameters(), weight_decay=0.01, scale=1048576
        )

Traceback (most recent call last):
  File "tune_cpm_ant.py", line 33, in <module>
    tune = config_dict["tune"](
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 291, in __init__
    super().__init__(**kwargs)
  File "/home/shanhoo3/fkb/remote_project/cpm/cpm-live/examples/tune.py", line 57, in __init__
    self.optimizer = bmt.optim.AdamOffloadOptimizer(
TypeError: __init__() got an unexpected keyword argument 'scale'

**Comment by zh-zheng** [comment]
use `pip install bmtrain==0.1.8.post1` for this project.
